server.port=${PORT:8080}
server.error.include-message=never
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
spring.thymeleaf.cache=true
server.servlet.session.tracking-modes=cookie
