package com.example.phishsim;
import org.springframework.stereotype.Component;import java.util.*;
@Component public class ScenarioRepository{
private final List<Scenario>s=List.of(
new Scenario(1,"Fake account password reset","Account Support","security-alert@micros0ft-support.invalid","Unusual sign-in activity detected","Hi,\n\nWe detected unusual sign-in activity. Verify within 24 hours:\n\nhttps://micros0ft-support.invalid/verify",true,List.of("Lookalike domain (micros0ft with a zero)","Urgency and threat of suspension","Generic greeting","Non-official domain"),"Open the official portal from a saved bookmark and review recent sign-ins.",Difficulty.BEGINNER),
new Scenario(2,"University IT maintenance notice","Example University IT","helpdesk@university.example","Planned maintenance window tonight","Hello,\n\nAuthentication maintenance is planned tonight from 11:00 PM to 1:00 AM. Contact the IT Help Desk through the campus portal if issues continue.",false,List.of("No request for sensitive information","Expected institutional domain and calm tone","Known support channel"),"Confirm maintenance through the university portal or status page.",Difficulty.INTERMEDIATE),
new Scenario(3,"Package delivery scam","Package Delivery","alerts@ups-tracking-secure.invalid","Delivery failed: action required","We could not complete delivery. Confirm your address and pay the re-delivery fee:\n\nhttp://ups-tracking-secure.invalid/update-address",true,List.of("Unexpected fee","Unencrypted HTTP link","Unofficial sender domain","Pressure to act"),"Open the carrier's official app and look up the tracking number there.",Difficulty.BEGINNER),
new Scenario(4,"Informational bank alert","Example Bank Alerts","alerts@bank.example","New device sign-in detected","We noticed a sign-in from a new device. If this was you, no action is needed. Otherwise, open your banking app. We never ask for your password by email.",false,List.of("Does not ask for credentials","Directs you to the official app","Clear safety reminder"),"Open the bank's official app directly and review account activity.",Difficulty.ADVANCED));
public List<Scenario>findAll(){return s;}public Optional<Scenario>findById(int id){return s.stream().filter(x->x.id()==id).findFirst();}}
